# Generated by Django 6.0.4 on 2026-04-07 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Contribuidor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("foto", models.ImageField(upload_to="docentes/")),
                (
                    "pagina_pessoal",
                    models.URLField(blank=True, verbose_name="LinkedIn ou Site"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("apresentacao", models.TextField()),
                ("objetivos", models.TextField()),
                ("num_semestres", models.IntegerField()),
                ("formato", models.CharField(max_length=100)),
                ("ects", models.IntegerField()),
                ("competencias_adquiridas", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_registo", models.DateField(auto_now_add=True)),
                ("fase", models.CharField(max_length=100)),
                ("descricao_opcao", models.TextField()),
                ("decisoes", models.TextField()),
                ("erros_correcoes", models.TextField()),
                ("uso_ai", models.TextField(verbose_name="Uso de IA")),
                ("foto", models.ImageField(upload_to="making_of/")),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("logo", models.ImageField(blank=True, upload_to="tecnologias/")),
                ("website", models.URLField(blank=True)),
                ("classificacao", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=200)),
                ("ano_inicio", models.IntegerField()),
                ("ano_fim", models.IntegerField(blank=True, null=True)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="formacoes", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("nivel", models.IntegerField(help_text="Nível de 1 a 5")),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="competencias", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("palavras_chave", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=200)),
                ("curso", models.CharField(max_length=200)),
                ("imagem", models.ImageField(upload_to="tfcs/")),
                ("ano", models.IntegerField()),
                ("resumo", models.TextField()),
                ("relatorio", models.FileField(upload_to="tfcs/relatorios/")),
                ("destaque", models.BooleanField(default=False)),
                (
                    "areas",
                    models.ManyToManyField(related_name="tfcs", to="portfolio.area"),
                ),
                (
                    "contribuidores",
                    models.ManyToManyField(
                        related_name="tfcs_colaborados", to="portfolio.contribuidor"
                    ),
                ),
                (
                    "docentes_orientadores",
                    models.ManyToManyField(
                        related_name="tfcs_orientados", to="portfolio.docente"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="tfcs", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("ects", models.IntegerField()),
                ("imagem", models.ImageField(blank=True, upload_to="ucs/")),
                (
                    "docentes",
                    models.ManyToManyField(related_name="ucs", to="portfolio.docente"),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UCS",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("conceitos", models.TextField()),
                ("curso", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("imagem", models.ImageField(upload_to="projetos/")),
                ("github", models.URLField(blank=True)),
                ("video", models.URLField(blank=True)),
                (
                    "contribuidores",
                    models.ManyToManyField(
                        related_name="projetos_colaborados", to="portfolio.contribuidor"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
                (
                    "uc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
