# Generated by Django 6.0.4 on 2026-04-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tfc",
            name="contribuidores",
        ),
        migrations.AlterField(
            model_name="tfc",
            name="palavras_chave",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
