# Generated by Django 6.0.4 on 2026-04-08 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_tfc_contribuidores_alter_tfc_palavras_chave"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadecurricular",
            name="bibliografia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="codigo_uc",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="curricularIUnitReadableCode",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="metodologia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="objetivos",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="programa",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="licenciatura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ucs",
                to="portfolio.licenciatura",
            ),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="semestre",
            field=models.CharField(max_length=20),
        ),
    ]
