# Generated by Django 6.0.4 on 2026-04-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_unidadecurricular_bibliografia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
