# Generated by Django 6.0.4 on 2026-04-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_projeto_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribuidor",
            name="pagina_pessoal",
            field=models.URLField(blank=True, verbose_name="LinkedIn ou Site"),
        ),
    ]
