# Generated by Django 6.0.4 on 2026-04-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_contribuidor_pagina_pessoal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="contribuidores",
            field=models.ManyToManyField(
                null=True,
                related_name="projetos_colaborados",
                to="portfolio.contribuidor",
            ),
        ),
    ]
