# Generated by Django 6.0.4 on 2026-04-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_projeto_contribuidores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="contribuidores",
            field=models.ManyToManyField(
                related_name="projetos_colaborados", to="portfolio.contribuidor"
            ),
        ),
    ]
