# Generated by Django 6.0.4 on 2026-04-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_projeto_contribuidores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makingof",
            name="foto",
            field=models.ImageField(null=True, upload_to="making_of/"),
        ),
    ]
