# Generated by Django 6.0.5 on 2026-05-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_alter_tfc_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="autor",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="curso",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="palavras_chave",
            field=models.TextField(blank=True, null=True),
        ),
    ]
