# Generated by Django 6.0.2 on 2026-05-04 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='artigos/')),
                ('link_externo', models.URLField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='artigos.artigo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_artigos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='GostoArtigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gostos', to='artigos.artigo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gostos_artigos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('artigo', 'user'), name='gosto_artigo_por_utilizador'), models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('artigo', 'session_key'), name='gosto_artigo_por_sessao')],
            },
        ),
    ]
